import Image from "next/image";
import { Card } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { InvoiceDetails } from "@/entities/dashboard/invoice";
import PrintButton from "./PrintButton";

interface InvoiceProps {
  data: InvoiceDetails;
}

export default function Invoice({ data }: InvoiceProps) {
  const {
    customer,
    company_address,
    company_phone,
    company_email,
    invoice_number,
    date,
    created,
    payment_method,
    services,
    vat_amount,
  } = data;

  const totalAmount = Number(customer?.price) + vat_amount;

  return (
    <div className=" min-h-screen  p-4 ">
      <div className="print-btn-container flex justify-center mb-8 print:hidden">
        <PrintButton title="Print Invoice" />
      </div>
      <Card className="p-6 shadow-md bg-white print:shadow-none invoice-print-area">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          <div className="header-left">
            <h4 className="font-bold text-gray-800 mb-2">
              Customer Information
            </h4>
            <p className="text-sm mb-1">
              <strong>Name:</strong> {customer.first_name} {customer.last_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Business:</strong> {customer.business_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Phone:</strong> {customer.phone_number}
            </p>
            <p className="text-sm mb-1">
              <strong>Email:</strong> {customer.email}
            </p>
            <p className="text-sm mb-1">
              <strong>TRN:</strong> {customer.tax_id}
            </p>
          </div>

          <div className="header-center flex flex-col items-center">
            <div className="relative w-24 h-24 mb-2">
              <Image
                src="/company-logo.png"
                alt="Company Logo"
                fill
                className="object-contain"
              />
            </div>
            <p className="text-sm text-center mb-1">{company_address}</p>
            <p className="text-sm text-center mb-1">Phone: {company_phone}</p>
            <p className="text-sm text-center mb-1">Email: {company_email}</p>
          </div>

          <div className="header-right">
            <h2 className="font-bold text-xl text-green-700 mb-2">
              Tax Invoice
            </h2>
            <p className="text-sm mb-1">
              <strong>Invoice Number:</strong> {invoice_number}
            </p>
            <p className="text-sm mb-1">
              <strong>TRN NO.</strong> 104668704000003
            </p>
            <p className="text-sm mb-1">
              <strong>Invoice Date:</strong> {date}
            </p>
            <p className="text-sm mb-1">
              <strong>Generated By:</strong> {created.name}
            </p>
            <p className="text-sm mb-1">
              <strong>Payment By:</strong> {payment_method}
            </p>
          </div>
        </div>

        <h3 className="font-bold text-lg text-green-700 border-b border-green-200 pb-2 mb-4">
          Service
        </h3>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Service Name</TableHead>
              <TableHead className="text-right">Price (AED)</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {services?.map((service: any, index: number) => (
              <TableRow key={index}>
                <TableCell>
                  {index + 1}. {service.name}
                </TableCell>
                <TableCell className="text-right">
                  AED {Number(service?.price || 0).toFixed(2)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>

        <h3 className="font-bold text-lg text-green-700 border-b border-green-200 pb-2 my-4">
          Total Summary
        </h3>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">
                VAT ({customer.vat_value}%)
              </TableCell>
              <TableCell className="text-right">
                AED {Number(vat_amount).toFixed(2)}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Total Amount</TableCell>
              <TableCell className="text-right font-bold">
                AED {totalAmount.toFixed(2)}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <div className="signed-by grid grid-cols-2 gap-8 my-8">
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Customer Signature
          </div>
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Authorized Signature
          </div>
        </div>

        <div className="footer mt-8 pt-4 border-t border-gray-200">
          <div className="bank-details mb-4 text-sm">
            <strong>Bank Details:</strong>
            <br />
            Account Holder Name: Holistic Legacy Accounting SPS LLC
            <br />
            Bank Name: Abu Dhabi Islamic Bank (ADIB)
            <br />
            Account No: 19326413
            <br />
            IBAN: AE720500000000019326413
            <br />
            Swift Code: ABDIAEAD
          </div>
          <div className="text-center text-xs text-gray-500">
            &copy; {new Date().getFullYear()} HOLISTIC LEGACY ACCOUNTING S.P.S
            L.L.C All Rights Reserved.
          </div>
        </div>
      </Card>
    </div>
  );
}
