export const RoleTypesOptions = {
    admin: "admin",
    operator: "operator",
    expert: "expert",
    "super-admin": "super-admin",
    supervisor: "supervisor",
} as const;

export const PermissionTypesOptions = {
    "user-create": "user-create",
    "user-edit": "user-edit",
    "user-delete": "user-delete",
    "profile-index": "profile-index",
    "role-list": "role-list",
    "role-create": "role-create",
    "role-edit": "role-edit",
    "role-delete": "role-delete",
    "permission-list": "permission-list",
    "permission-create": "permission-create",
    "permission-edit": "permission-edit",
    "permission-delete": "permission-delete",
    "file-manager": "file-manager",
    "websetting-edit": "websetting-edit",
    "user-activity": "user-activity",
    "log-view": "log-view",
    "branches-list": "branches-list",
    "branches-create": "branches-create",
    "branches-edit": "branches-edit",
    "branches-delete": "branches-delete",
    "services-edit": "services-edit",
    "services-delete": "services-delete",
    "services-list": "services-list",
    "services-create": "services-create",
    "customers-list": "customers-list",
    "customers-create": "customers-create",
    "customers-edit": "customers-edit",
    "customers-delete": "customers-delete",
    "customers-view": "customers-view",
    "customers-upload-media": "customers-upload-media",
    "customers-delete-media": "customers-delete-media",
    "customers-status": "customers-status",
    "dashboard": "dashboard",
    "can-see-all-branches-data": "can-see-all-branches-data",
    "customers-account": "customers-account",
    "cmspage-list": "cmspage-list",
    "cmspage-create": "cmspage-create",
    "cmspage-edit": "cmspage-edit",
    "cmspage-delete": "cmspage-delete",
    "cmscategory-list": "cmscategory-list",
    "cmscategory-create": "cmscategory-create",
    "cmscategory-edit": "cmscategory-edit",
    "cmscategory-delete": "cmscategory-delete",
    "shift-edit": "shift-edit",
    "shift-delete": "shift-edit",
    "shift-status": "shift-status",
    
} as const;

