import Image from "next/image";
import { Card } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { InvoiceDetails } from "@/entities/dashboard/invoice";
import PrintButton from "../../invoice/components/PrintButton";
import CompanyLogo from "@/public/images/dashboard/commn/Group 8.png";

interface ReceiptProps {
  data: InvoiceDetails;
}

export default function Receipt({ data }: ReceiptProps) {
  const {
    customer,
    company_address: companyAddress,
    company_phone: companyPhone,
    company_email: companyEmail,
    invoice_number: invoiceNumber,
    date,
    created,
    payment_method: paymentMethod,
    services,
    vat_amount: vatAmount,
  } = data;
  const total_amount = customer.price + vatAmount;

  return (
    <div className="min-h-screen  p-4 ">
      <div className="print-btn-container flex justify-center mb-8 print:hidden">
        <PrintButton title=" Print Receipt" />
      </div>
      <Card className="p-6 shadow-md bg-white invoice-print-area print:shadow-none">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          <div className="header-center flex flex-col items-center">
            <div className="relative w-70 h-70 mb-[-20%] mt-[-20%]">
              <Image
                src={CompanyLogo}
                alt="Company Logo"
                fill
                className="object-contain"
              />
            </div>
          </div>

          <div className="header-left ml-20 text-[#7E7E7E] mt-3">
            <h4 className="font-bold text-[#000000] mb-2">
              Customer Information
            </h4>
            <p className="text-sm mb-1">
              <strong>Name:</strong> {customer.first_name} {customer.last_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Business:</strong> {customer.business_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Phone:</strong> {customer.phone_number}
            </p>
            <p className="text-sm mb-1">
              <strong>Email:</strong> {customer.email}
            </p>
            <p className="text-sm mb-1">
              <strong>TRN:</strong> {customer.tax_id}
            </p>
          </div>

          <div className="header-right   text-[#7E7E7E] ml-20 mt-3">
            <h2 className="font-bold text-[#000000] mb-2">Receipt</h2>

            <p className="text-sm mb-1">
              <strong>Receipt Number:</strong> {invoiceNumber}
            </p>
            <p className="text-sm mb-1">
              <strong>Receipt Date:</strong> {date}
            </p>
            <p className="text-sm mb-1">
              <strong>Generated By:</strong> {created.name}
            </p>
            <p className="text-sm mb-1">
              <strong>Payment By:</strong> {paymentMethod}
            </p>
          </div>
        </div>



        <h3 className="font-bold text-lg text-green-700 mb-2 font-montserrat">
          Payment Details
        </h3>
        <div className="bg-[#F5F9F6] rounded-md overflow-hidden mb-4">
          <div className="grid grid-cols-2 px-4 py-2 bg-[#00713a0b] text-sm font-semibold text-gray-600 border-gray-300 font-montserrat">
            <div>Description</div>
            <div className="text-right">Amount ( AED )</div>
          </div>
          {services?.map((service: any, index: number) => (
            <div
              key={index}
              className="grid grid-cols-2 px-4 py-2 text-sm text-gray-800 border-b border-gray-100 font-montserrat"
            >
              <div>                  {index + 1}. {service.name}
              </div>
              <div className="text-right text-[#7E7E7E]">
                AED {service.price}
                {/* <span className="text-xs">AED</span> */}
              </div>
            </div>
          ))}
        </div>



        <h3 className="font-bold text-lg text-green-700 mb-2 font-montserrat">
          Total Paid
        </h3>

        <div className="rounded-md overflow-hidden font-montserrat">
          <div className="flex justify-between px-4 py-2 bg-[#e8811918] font-semibold text-sm text-gray-500">
            <span>Base Amount</span>
            <span className="text-gray-500 font-semibold">
              <span className="text-black text-[16px] font-bold">
                AED {customer.price}                </span>
            </span>
          </div>
          <div className="flex justify-between px-4 py-2 bg-[#e8811918] font-semibold text-gray-500 mt-2">
            <span>VAT (%)</span>
            <span className="text-orange-600 text-[16px] font-bold">
            AED {Number(vatAmount)}
            {/* <span className="text-gray-500">AED</span> */}
            </span>
          </div>
          <div className="flex justify-between px-4 py-2 bg-[#e8811918] font-semibold text-gray-500 mt-2">
            <span>Total Paid</span>
            <span className="text-orange-600 text-[16px] font-bold">
            AED {Number(total_amount)}
            {/* <span className="text-gray-500">AED</span> */}
            </span>
          </div>
        </div>
       

        <div className="signed-by grid grid-cols-2 gap-8 my-8">
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Customer Signature
          </div>
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Authorized Signature
          </div>
        </div>

        <div className="footer mt-8 pt-4 border-t border-gray-200 text-center text-xs text-gray-500">
          &copy; {new Date().getFullYear()} HOLISTIC LEGACY ACCOUNTING S.P.S
          L.L.C All Rights Reserved.
        </div>
      </Card>
    </div>
  );
}
