import Image from "next/image";
import { Card } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { InvoiceDetails } from "@/entities/dashboard/invoice";
import PrintButton from "../../invoice/components/PrintButton";

interface ReceiptProps {
  data: InvoiceDetails;
}

export default function Receipt({ data }: ReceiptProps) {
  const {
    customer,
    company_address: companyAddress,
    company_phone: companyPhone,
    company_email: companyEmail,
    invoice_number: invoiceNumber,
    date,
    created,
    payment_method: paymentMethod,
    services,
    vat_amount: vatAmount,
  } = data;
  const total_amount = customer.price + vatAmount;

  return (
    <div className="min-h-screen  p-4 ">
      <div className="print-btn-container flex justify-center mb-8 print:hidden">
        <PrintButton title=" Print Receipt" />
      </div>
      <Card className="p-6 shadow-md bg-white invoice-print-area print:shadow-none">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          <div className="header-left">
            <h4 className="font-bold text-gray-800 mb-2">
              Customer Information
            </h4>
            <p className="text-sm mb-1">
              <strong>Name:</strong> {customer.first_name} {customer.last_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Business:</strong> {customer.business_name}
            </p>
            <p className="text-sm mb-1">
              <strong>Phone:</strong> {customer.phone_number}
            </p>
            <p className="text-sm mb-1">
              <strong>Email:</strong> {customer.email}
            </p>
            <p className="text-sm mb-1">
              <strong>TRN:</strong> {customer.tax_id}
            </p>
          </div>

          <div className="header-center flex flex-col items-center">
            <div className="relative w-24 h-24 mb-2">
              <Image
                src="/company-logo.png"
                alt="Company Logo"
                fill
                className="object-contain"
              />
            </div>
            <p className="text-sm text-center mb-1">{companyAddress}</p>
            <p className="text-sm text-center mb-1">Phone: {companyPhone}</p>
            <p className="text-sm text-center mb-1">Email: {companyEmail}</p>
          </div>

          <div className="header-right">
            <h2 className="font-bold text-xl text-primary mb-2">Receipt</h2>
            <p className="text-sm mb-1">
              <strong>Receipt Number:</strong> {invoiceNumber}
            </p>
            <p className="text-sm mb-1">
              <strong>Receipt Date:</strong> {date}
            </p>
            <p className="text-sm mb-1">
              <strong>Generated By:</strong> {created.name}
            </p>
            <p className="text-sm mb-1">
              <strong>Payment By:</strong> {paymentMethod}
            </p>
          </div>
        </div>

        <h3 className="font-bold text-lg text-primary border-b border-red-200 pb-2 mb-4">
          Payment Details
        </h3>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Description</TableHead>
              <TableHead className="text-right">Amount (AED)</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {services.map((service: any, index: number) => (
              <TableRow key={index}>
                <TableCell>
                  {index + 1}. {service.name}
                </TableCell>
                <TableCell className="text-right">
                  AED {service.price.toFixed(2)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>

        <h3 className="font-bold text-lg text-primary border-b border-red-200 pb-2 my-4">
          Total Paid
        </h3>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">Base Amount</TableCell>
              <TableCell className="text-right">AED {customer.price}</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">VAT (%)</TableCell>
              <TableCell className="text-right">
                AED {Number(vatAmount)?.toFixed(2)}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Total Paid</TableCell>
              <TableCell className="text-right font-bold">
                AED {Number(total_amount).toFixed(2)}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <div className="signed-by grid grid-cols-2 gap-8 my-8">
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Customer Signature
          </div>
          <div className="signature-box border-t-2 border-gray-300 pt-2 text-center">
            Authorized Signature
          </div>
        </div>

        <div className="footer mt-8 pt-4 border-t border-gray-200 text-center text-xs text-gray-500">
          &copy; {new Date().getFullYear()} HOLISTIC LEGACY ACCOUNTING S.P.S
          L.L.C All Rights Reserved.
        </div>
      </Card>
    </div>
  );
}
