export interface ISelectOption {
  label: string;
  value: string | number;
  otherValues?: { [type: string]: { value: string | number } };
}
export type RoleTypes = "admin" | "operator" |"expert"| "super-admin"|"supervisor" 
export type PermissionTypes = 
  | "user-create"
  | "user-edit"
  | "user-delete"
  | "profile-index"
  | "role-list"
  | "role-create"
  | "role-edit"
  | "role-delete"
  | "permission-list"
  | "permission-create"
  | "permission-edit"
  | "permission-delete"
  | "file-manager"
  | "websetting-edit"
  | "user-activity"
  | "log-view"
  | "branches-list"
  | "branches-create"
  | "branches-edit"
  | "branches-delete"
  | "services-edit"
  | "services-delete"
  | "services-list"
  | "services-create"
  | "customers-list"
  | "customers-create"
  | "customers-edit"
  | "customers-delete"
  | "customers-view"
  | "customers-upload-media"
  | "customers-delete-media"
  | "customers-status"
  | "dashboard"
  | "can-see-all-branches-data"
  | "customers-account"
  | "cmspage-list"
  | "cmspage-create"
  | "cmspage-edit"
  | "cmspage-delete"
  | "cmscategory-list"
  | "cmscategory-create"
  | "cmscategory-edit"
  | "cmscategory-delete";


